swagger: '2.0'
info:
  version: '1.0.0'
  title: Swagger Definition for Risk Score Calcultion
  description: REST API that for calculating risk score for authentication requests
paths:
  /ping:
    get:
      responses:
        '200':
          description: OK
  /getRiskScore:
    post:
      description: Method to obtain the calculated risk score an authentication request
      operationId: getRiskScore
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - name: authRequest
          in: body
          description: authentication request by the user
          required: true
          schema:
            $ref: '#/definitions/authRequest'
      responses:
        '200':
          description: Risk Score
          schema:
            $ref: '#/definitions/riskScore'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  authRequest:
    type: object
    required:
      - contextId
      - eventId
      - eventType
      - authenticationSuccess
      - username
      - localUsername
      - userStoreDomain
      - tenantDomain
      - remoteIp
      - region
      - inboundAuthType
      - serviceProvider
      - rememberMeEnabled
      - forceAuthEnabled
      - passiveAuthEnabled
      - rolesCommaSeparated
      - authenticationStep
      - identityProvider
      - authStepSuccess
      - stepAuthenticator
      - isFirstLogin
      - identityProviderType
      - timestamp
    properties:
      contextId:
        type: string
      eventId:
        type: string
      eventType:
        type: string
      authenticationSuccess:
        type: boolean
      username:
        type: string
      localUsername:
        type: string
      userStoreDomain:
        type: string
      tenantDomain:
        type: string
      remoteIp:
        type: string
      region:
        type: string
      inboundAuthType:
        type: string
      serviceProvider:
        type: string
      rememberMeEnabled:
        type: boolean
      forceAuthEnabled:
        type: boolean
      passiveAuthEnabled:
        type: boolean
      rolesCommaSeparated:
        type: string
      authenticationStep:
        type: string
      identityProvider:
        type: string
      authStepSuccess:
        type: boolean
      stepAuthenticator:
        type: string
      isFirstLogin:
        type: boolean
      identityProviderType:
        type: string
      timestamp:
        type: long

  riskScore:
    type: object
    required:
      - eventID
      - score
    properties:
      eventID:
        type: string
      score :
        type: integer

  errorModel:
    type: object
    required:
      - status
      - code
      - message
      - additionalDetails
    properties:
      status:
        type: string
      code:
        type: string
      message:
        type: string
      additionalDetails:
        type: string

